spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.22:8848


  application:
    name: gulimall-third-party

server:
  port: 8090

logging:
  level:
    com.atg.security: debug
